name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version to publish"
        required: true

jobs:
  build-bionic:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Hicn Repository"
        uses: actions/checkout@master
        with:
          repository: "icn-team/hicn"
          fetch-depth: 0
          ref: v${{ github.event.inputs.release_version }}
      - name: "Check if release ${{ github.event.inputs.release_version }} can be built"
        shell: bash
        run: |
          NEXT_TAG=$(git tag --contains=v${{ github.event.inputs.release_version }} | sed -n 2p)
          git checkout ${NEXT_TAG}
          echo "tag=${NEXT_TAG}" >> $GITHUB_ENV
          echo "commitish=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: "Build artifacts"
        shell: bash
        run: |
          bash scripts/build-packages.sh
          ls scripts
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          repo: "hicn"
          owner: "icn-team"
          tag_name: "${{ env.tag }}"
          commitish: "${{ env.commitish }}"
          release_name: "${{ github.event.inputs.release_version }}"
          draft: false
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-light_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-plugin_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-3
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-utils-memif_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-4
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicn-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-5
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicn_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-6
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicnctrl-memif-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-7
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicntransport-memif-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-8
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicntransport-memif_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-9
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-utils_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-10
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicnctrl-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-11
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicnctrl_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-12
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicntransport-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-13
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicntransport_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "facemgr_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-apps-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-plugin-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-apps-memif_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-apps-memif-dev_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "libhicnctrl-memif_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-apps_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload-release-asset-14
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          asset: "hicn-collectd-plugins_${{ github.event.inputs.release_version }}-release_amd64.deb"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/${{ env.asset }}"
          asset_name: "${{ env.asset }}"
          asset_content_type: application/octet-stream
