name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version to publish"
        required: true

jobs:
  build-bionic:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Hicn Repository"
        uses: actions/checkout@master
        with:
          repository: "icn-team/hicn"
          fetch-depth: 0
          ref: v${{ github.event.inputs.release_version }}
      - name: "Check if release ${{ github.event.inputs.release_version }} can be built"
        shell: bash
        run: |
          NEXT_TAG=$(git tag --contains=v${{ github.event.inputs.release_version }} | sed -n 2p)
          git checkout ${NEXT_TAG}
          echo "tag=${NEXT_TAG}" >> $GITHUB_ENV
          echo "commitish=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: "Build artifacts"
        shell: bash
        run: |
          echo bash scripts/build-packages.sh
          mkdir build
          echo "Binary file" > build/build.deb
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          repo: "hicn"
          owner: "icn-team"
          tag_name: "${{ env.tag }}"
          commitish: "${{ env.commitish }}"
          release_name: "${{ github.event.inputs.release_version }}"
          draft: false
          prerelease: false
      - name: Upload Release Assets - Debs
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/"
          asset_name: "build.deb"
          asset_content_type: application/octet-stream
