name: Build and Deploy
on:
  schedule:
    - cron: "30 1 * * *"
  push:
jobs:
  build-bionic:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Hicn Repository"
        uses: actions/checkout@master
        with:
          repository: "FDio/hicn"
          fetch-depth: 0
          ref: v20.09
      - name: "Build artifacts and publish"
        shell: bash
        run: |
          bash scripts/build-packages.sh
      - name: "Remove old assets"
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: |
          ASSETS_IDS=$(curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/icn-team/workflows/releases/tags/release" | jq -r '.assets[]' | jq -r '.id');for ASSET_ID in $ASSETS_IDS ; do curl -X DELETE --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/icn-team/workflows/releases/assets/$ASSET_ID"; done;
      - name: Upload Release Asset (hICN_Tools)
        if: github.ref == 'refs/heads/master'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/icn-team/workflows/releases/21250805/assets{?name,label}
          asset_path: ./build
          asset_name: "*.deb"
          asset_content_type: application/zip
