name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version to publish"
        required: true

jobs:
  build-bionic:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Hicn Repository"
        uses: actions/checkout@master
        with:
          repository: "icn-team/hicn"
          fetch-depth: 0
          ref: test
      - name: "Build artifacts"
        shell: bash
        run: |
          bash scripts/build-packages.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Assets - Debs
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./build/"
          asset_name: "*.deb"
